### ISSUE TITLE
There buttons to flip the image stack but not flip the axes. 

### ISSUE THREAD

**Issue by raacampbell** [SainsburyWellcomeCentre/lasagna#136]
Should I change the image stack flip buttons to axis flip buttons? That way all plot elements will flip.

**Comment by raacampbell13** [comment]
Yes, it should be this way (don't flip the stack). This is the **axis** tab so it should manipulate axes. We can have some other solution for flipping and saving whole stacks. Maybe a plugin?

**Comment by raacampbell** [comment]
This amounts to a bug, because if a user flips the image stack then traces points. The points aren't in the positions they thought they were in.

**Comment by raacampbell** [comment]
Use the invert axes methods from PyQtGraph. Now the axes flip too. Now the coordinates of points follow the expected. Note the coordinates in the bottom left:
![Screen Shot 2020-04-08 at 16 15 49](https://user-images.githubusercontent.com/5427811/78802281-8a9fee80-79b5-11ea-80a8-f3d3c2d2127b.png)
 
![Screen Shot 2020-04-08 at 16 16 01](https://user-images.githubusercontent.com/5427811/78802293-8d9adf00-79b5-11ea-8f37-4bf8c3f814e9.png)

**Comment by raacampbell** [comment]
Users report this works.
