### ISSUE TITLE
the embeded console doesn't work

### ISSUE THREAD

**Issue by ablot** [SainsburyWellcomeCentre/lasagna#173]
Starting with `-C` doesn't work for me. It starts an Ipython instance but doesn't start the GUI.

My fork has a `embeded_ipython` branch that give a semi-working work around. It changes the call of the Qt app to use that create by Ipython if there is such app. So starting with `python lasagna.py` or `ipython lasagna.py` does a non-interactive run but starting `ipython --gui=qt` and then `%run lasagna.py` keeps the ipython console active.  There is still an issue. When having a ipython console and a running GUI the console needs to be exited first. Closing the GUI doesn't work and make the terminal unusable.

I still think the option of having the interactive console is extremely useful for debugging and development but not ready to go to master like that.

@raacampbell, let me know if I still should merge it in develop or if you found a way to keep the `-C` flag working.

**Comment by ablot** [comment]
Actually my branch start a console in the wrong scope ... I'll try to have a look at that tonight

**Comment by raacampbell** [comment]
Ok, just let me know. I think we're definitely clear to merge into the my dev branch. Remember that not many people are even using the master branch. So if you add a feature that is incomplete and doesn't impact other functionality, then I don't see the problem. There shit loads of bugs anyway. Just look at the issue tracker.

**Comment by raacampbell** [comment]
Did you manage to get this working? It would be useful.

**Comment by ablot** [comment]
It works ... more or less. If you start `python lasagna.py -C` you have a working console and a frozen GUI. Then you need to send `%gui qt` in the console to wake up the GUI. That works fine. Closing everything down cleaning is still a bit experimental (might freeze the GUI or the console)

**Comment by ablot** [comment]
That works for me. Let me know if I can close this

**Comment by raacampbell** [comment]
Awesome!

**Comment by raacampbell** [comment]
Added docs on starting it to: https://github.com/SainsburyWellcomeCentre/lasagna/wiki/Developer-How-To

**Comment by raacampbell** [comment]
Added traitlets and ipython to the requirements and yml files (1d7c93e49d5904a5550b4a0f1be5ef025413fdb3)
