### ISSUE TITLE
Add point removal to line drawing plugin

### ISSUE THREAD

**Issue by raacampbell** [SainsburyWellcomeCentre/lasagna#203]

**Comment by raacampbell** [comment]
By this point we can do all the fitting we need (c28a8796c680550205e285534a73f90d3281138f), so it's really just a case of adding the point removal. The plugin will then be minimally useful for tracing. 

It would be ideal if it's possible to add the highlighted point. So we know what we are about to delete. I think it should be possible to do this safely without having to add a plot ingredient. _I think also that it would be nice to only add the line ingredient if the user has accepted the fit. Otherwise don't add it._

**Comment by raacampbell** [comment]
Removal works: 88c7b6911466e5da6f301cb348e29de54676f80f

@ablot do you care about the first data column in the table (point ID)? I'm thinking of removing it.  I also made the QTable non-editable (8ec75fe97f017b01abf79ab0a91438b6d5e41aee). As it didn't seem important and it's confusing unless edits trigger a slot to update the plot elements.

**Comment by ablot** [comment]
I don't care about the ID. I kept it in case we wanted to label points (for instance channel numbers) but I have never used it.

**Comment by raacampbell** [comment]
ID column removed: 7c283de5548c579568fd2725fbfd7c924ddba015

**Comment by raacampbell** [comment]
Point removal has the problem that the highlight point remains and gives the impression that nothing was removed. Fix this: 22d3cfd40654c6af712d7b9284e2f2e03a3144f2
