### ISSUE TITLE
Zooming in with the mouse wheel does not work with latest numpy version

### ISSUE THREAD

**Issue by guidomeijer** [SainsburyWellcomeCentre/lasagna#252]
After a clean install on a new computer I couldn't use the mouse wheel to zoom in anymore. The console showed this error:
```
File "C:\Users\guido\mambaforge\envs\lasagna\Lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
Traceback (most recent call last):
  File "c:\users\guido\repositories\lasagna\lasagna\lasagna_viewBox.py", line 44, in wheelEvent
    self.onMouseWheeled(ev, axis)
  File "c:\users\guido\repositories\lasagna\lasagna\lasagna_viewBox.py", line 148, in onMouseWheeled
    mask = np.array(self.state["mouseEnabled"], dtype=np.float)
```
After numpy 1.20 the np.float alias was deprecated, resulting in this error. The numpy version which is installed while creating the environment is the latest version (1.24). Reinstalling the environment after specifying numpy=1.20 in the lasagna_environment.yml file fixed this issue.

**Comment by micheleangelofabbri** [comment]
This PR corrects the incompatibility https://github.com/SainsburyWellcomeCentre/lasagna/pull/253

**Comment by raacampbell** [comment]
Thanks for the fix.
