### ISSUE TITLE
Type of images

### ISSUE THREAD

**Issue by imontiel92** [SainsburyWellcomeCentre/lasagna#254]
Is it possible to use the GUI lasagna with individual slice images? I cut the brain into sagittal slices and took a picture under the microscope afterwards.  The images has a tiff format. Thank you in advance.

**Comment by raacampbell** [comment]
I guess it would work but it's not really what the software is for. I suggest you try Napari. Lasagna isn't being actively developed any more, although there is a very small user community.

**Comment by imontiel92** [comment]
Thank you.
